In [5]:
import pandas as pd
import numpy as np

In [7]:
master_df=pd.read_csv(r"D:\RCM\Cleaned data\Master_df.xls")

# Master KPI Table

In [60]:
KPI_Table = pd.DataFrame(columns=["Category", "KPI","Value"])

In [64]:
KPI_Table

Empty DataFrame
Columns: [Category, KPI, Value]
Index: []

# KPI Function

In [69]:
def add_kpi(category, kpi, value):

    global KPI_Table

    KPI_Table.loc[len(KPI_Table)] = [category,kpi,value]

# ________________________ Executive KPIs _________________________

In [76]:
add_kpi("Executive","Total Claims",master_df["Claim_ID"].nunique())

add_kpi("Executive","Total Revenue",round(master_df["Net_Realized_Revenue"].sum(),2))

add_kpi("Executive","Total Collections",round(master_df["Total_Collections_Posted"].sum(),2))

add_kpi("Executive","Outstanding Amount",round(master_df["Outstanding_Amount"].sum(),2))

add_kpi("Executive","Net Profit",round(master_df["Net_Profit"].sum(),2))

add_kpi("Executive","Profit Margin %",round(master_df["Profit_Margin"].mean(),2))

add_kpi("Executive","Collection %",round((master_df["Total_Collections_Posted"].sum() /master_df["Net_Billed_Amount"].sum()) * 100,2))

add_kpi("Executive","Approval %",round((master_df["Approval_Flag"]=="Approved").mean()*100, 2))

add_kpi("Executive","Denial %",round((master_df["Denial_Flag"]=="Yes").mean()*100,2 ))

add_kpi("Executive","Average Settlement Days",round(master_df["Days_to_Payment_Settlement"].mean(),2))

In [78]:
KPI_Table

    Category                      KPI       Value
0  Executive             Total Claims      515.00
1  Executive            Total Revenue  7220030.18
2  Executive        Total Collections  6401545.70
3  Executive       Outstanding Amount  1140505.15
4  Executive               Net Profit  6272798.21
5  Executive          Profit Margin %       87.27
6  Executive             Collection %       84.88
7  Executive               Approval %       71.35
8  Executive                 Denial %        6.35
9  Executive  Average Settlement Days       47.38

# ___________________________ Revenue KPIs ___________________________

In [82]:
add_kpi("Revenue","Total Net Billed Amount",round(master_df["Net_Billed_Amount"].sum(),2))

add_kpi("Revenue","Total Net Billed Amount",round(master_df["Net_Billed_Amount"].sum(),2))

add_kpi("Revenue","Average Revenue per Claim",round(master_df["Net_Realized_Revenue"].sum()/master_df["Claim_ID"].nunique(),2))

add_kpi("Revenue","Average Revenue per Patient",round(master_df["Net_Realized_Revenue"].sum()/master_df["Patient_ID"].nunique(),2))

add_kpi("Revenue","Highest Revenue Department",master_df.groupby("Department_Name")["Net_Realized_Revenue"].sum().idxmax())

add_kpi("Revenue","Highest Revenue Insurance Company",master_df.groupby("Insurance_Company")["Net_Realized_Revenue"].sum().idxmax())

In [86]:
KPI_Table[KPI_Table["Category"]=="Revenue"]

   Category                                KPI          Value
10  Revenue            Total Net Billed Amount     7542050.85
11  Revenue            Total Net Billed Amount     7542050.85
12  Revenue          Average Revenue per Claim       14019.48
13  Revenue        Average Revenue per Patient       15764.26
14  Revenue         Highest Revenue Department      Emergency
15  Revenue  Highest Revenue Insurance Company  National Care

# _____________________________ Collection KPIs ________________________________

In [90]:
add_kpi("Collection","Outstanding Amount",round(master_df["Outstanding_Amount"].sum(),2))


add_kpi("Collection","Collection Gap",round((
            master_df["Net_Billed_Amount"] -master_df["Total_Collections_Posted"]).sum(), 2 ))


add_kpi("Collection","Average Collection per Claim",round(
        master_df["Total_Collections_Posted"].sum()/master_df["Claim_ID"].nunique(),2))


add_kpi("Collection","Average Collection per Patient",round(
        master_df["Total_Collections_Posted"].sum()/master_df["Patient_ID"].nunique(),2))


add_kpi("Collection","Average Payment Settlement Days",round(master_df["Days_to_Payment_Settlement"].mean(),2))


add_kpi("Collection","Pending Collection %",round((
            master_df["Outstanding_Amount"].sum()/master_df["Net_Billed_Amount"].sum())*100,2))

In [92]:
KPI_Table[KPI_Table["Category"]=="Collection"]

      Category                              KPI       Value
16  Collection               Outstanding Amount  1140505.15
17  Collection                   Collection Gap  1140505.15
18  Collection     Average Collection per Claim    12430.19
19  Collection   Average Collection per Patient    13977.17
20  Collection  Average Payment Settlement Days       47.38
21  Collection             Pending Collection %       15.12

# ________________________________ Claim KPIs ______________________________

In [110]:
add_kpi("Claim","Total Claims Submitted",master_df["Claim_ID"].nunique())

add_kpi("Claim","High Value Claim %",round((master_df["High_Value_Claim"]=="Yes").mean()*100,2))

add_kpi("Claim","Average Submission Attempts",round(master_df["Submission_Attempts_Count"].mean(),2))

add_kpi("Claim","Average Claim Processing Time (Hours)",round(master_df["Case_Processing_Time_Hours"].mean(),2))

In [112]:
KPI_Table[KPI_Table["Category"]=="Claim"]

   Category                                    KPI  Value
22    Claim                 Total Claims Submitted    515
23    Claim                     High Value Claim %    0.0
24    Claim            Average Submission Attempts   1.14
25    Claim  Average Claim Processing Time (Hours)  22.24

# _____________________________ AR KPIs ____________________________

In [128]:
add_kpi("AR","Average AR Balance per Claim",round(master_df["Outstanding_AR_Balance"].sum()/master_df["Claim_ID"].nunique(),2))

add_kpi("AR","Average AR Balance per Patient",round(master_df["Outstanding_AR_Balance"].sum()/master_df["Patient_ID"].nunique(),2))

add_kpi("AR","Partial Payment %",round((master_df["Payment_Status"]=="Partial").mean()*100,2))

add_kpi("AR","Pending Payment %",round((master_df["Payment_Status"]=="Pending").mean()*100,2))

add_kpi("AR","Fully Paid %",round((master_df["Payment_Status"]=="Paid").mean()*100,2))

In [130]:
KPI_Table[KPI_Table["Category"]=="AR"]

   Category                             KPI    Value
26       AR    Average AR Balance per Claim  1589.29
27       AR  Average AR Balance per Patient  1787.08
28       AR               Partial Payment %    26.15
29       AR               Pending Payment %    10.77
30       AR                    Fully Paid %    63.08

# __________________________ Patient KPIs  ___________________________

In [143]:
add_kpi("Patient","Total Patients",master_df["Patient_ID"].nunique())

add_kpi("Patient","Chronic Patient %",round((master_df["Chronic_Patient"]=="Yes").mean()*100,2))

add_kpi("Patient","Adult Patient %",round((master_df["Age_Group"]=="Adult").mean()*100,2))

add_kpi("Patient","Senior Patient %",round((master_df["Age_Group"]=="Senior").mean()*100,2))

In [145]:
KPI_Table[KPI_Table["Category"]=="Patient"]

   Category                KPI  Value
31  Patient     Total Patients    458
32  Patient  Chronic Patient %  13.65
33  Patient    Adult Patient %  55.96
34  Patient   Senior Patient %  23.85

# _____________________________ Provider KPIs  ___________________________

In [148]:
add_kpi("Provider","Total Providers",master_df["Provider_ID"].nunique())

add_kpi("Provider","Average Revenue per Provider",round(master_df["Net_Realized_Revenue"].sum()/master_df["Provider_ID"].nunique(),2))

add_kpi("Provider","Average Collection per Provider",round(master_df["Total_Collections_Posted"].sum()/master_df["Provider_ID"].nunique(),2))

add_kpi("Provider","Average Provider Experience",round(master_df["Experience_Years"].mean(),2))

In [150]:
KPI_Table[KPI_Table["Category"]=="Provider"]

    Category                              KPI     Value
35  Provider                  Total Providers       219
36  Provider     Average Revenue per Provider  32968.17
37  Provider  Average Collection per Provider   29230.8
38  Provider      Average Provider Experience     18.98

# _____________________________ Insurance KPIs ____________________________

In [164]:
add_kpi("Insurance","Total Insurance Companies",master_df["Insurance_Company"].nunique())

add_kpi("Insurance","Average Coverage %",round(master_df["Coverage_Percentage"].mean(),2))

add_kpi("Insurance","High Coverage Category %",round((master_df["Coverage_Category"]=="High").mean()*100,2))

add_kpi("Insurance","High Insurance Risk %",round((master_df["Insurance_Risk"]=="High").mean()*100,2))

In [166]:
KPI_Table[KPI_Table["Category"]=="Insurance"]

     Category                        KPI  Value
39  Insurance  Total Insurance Companies      8
40  Insurance         Average Coverage %  85.13
41  Insurance   High Coverage Category %  48.65
42  Insurance      High Insurance Risk %    0.0

# ___________________________ Operational KPIs  ___________________________

In [172]:
add_kpi("Operational","Automation Rate %",round((master_df["Automation_Assisted_Flag"]=="Yes").mean()*100,2))

add_kpi("Operational","Average Manual Overrides",round(master_df["Manual_Override_Count"].mean(),2))

add_kpi("Operational","Average Resource Efficiency",round(master_df["Resource_Efficiency_Score"].mean(),2))

add_kpi("Operational","Average System Touchpoints",round(master_df["System_Touchpoints_Count"].mean(),2))

In [174]:
KPI_Table[KPI_Table["Category"]=="Operational"]

       Category                          KPI Value
43  Operational            Automation Rate %   0.0
44  Operational     Average Manual Overrides  0.13
45  Operational  Average Resource Efficiency   4.2
46  Operational   Average System Touchpoints  1.81

# _____________________________ Financial KPIs  ___________________________

In [177]:
add_kpi("Financial","Total Net Profit",round(master_df["Net_Profit"].sum(),2))

add_kpi("Financial","Average Profit Margin %",round(master_df["Profit_Margin"].mean(),2))

add_kpi("Financial","Total Write-Off Amount",round(master_df["Write_Off_Amount"].sum(),2))

add_kpi("Financial","Average Operating Margin %",round(master_df["Operating_Margin_Percentage"].mean(),2))

add_kpi("Financial","Average Billing Cost per Claim",round(master_df["Cost_of_Billing_Operations"].sum()/master_df["Claim_ID"].nunique(),2))

In [179]:
KPI_Table[KPI_Table["Category"]=="Financial"]

     Category                             KPI       Value
47  Financial                Total Net Profit  6272798.21
48  Financial         Average Profit Margin %       87.27
49  Financial          Total Write-Off Amount   322020.67
50  Financial      Average Operating Margin %       97.85
51  Financial  Average Billing Cost per Claim       250.0

# ___________________________ Productivity KPIs  ________________________

In [183]:
add_kpi("Productivity","Average Productivity Index",round(master_df["Productivity_Index"].mean(),2))

add_kpi("Productivity","Average Quality Score",round(master_df["Quality_Score"].mean(),2))

add_kpi("Productivity","Average Attendance %",round(master_df["Attendance_Percentage"].mean(),2))

add_kpi("Productivity","Average Training Hours",round(master_df["Training_Hours"].mean(),2))

In [185]:
KPI_Table[KPI_Table["Category"]=="Productivity"]

        Category                         KPI  Value
52  Productivity  Average Productivity Index  88.22
53  Productivity       Average Quality Score   90.6
54  Productivity        Average Attendance %  93.64
55  Productivity      Average Training Hours   39.8

# ___________________________ Final Validation ___________________________

## Total KPIs

In [193]:
len(KPI_Table)

56

In [190]:
KPI_Table["Category"].value_counts()

Category
Executive       10
Revenue          6
Collection       6
AR               5
Financial        5
Claim            4
Patient          4
Provider         4
Insurance        4
Operational      4
Productivity     4
Name: count, dtype: int64

In [195]:
KPI_Table

        Category                                    KPI          Value
0      Executive                           Total Claims          515.0
1      Executive                          Total Revenue     7220030.18
2      Executive                      Total Collections      6401545.7
3      Executive                     Outstanding Amount     1140505.15
4      Executive                             Net Profit     6272798.21
5      Executive                        Profit Margin %          87.27
6      Executive                           Collection %          84.88
7      Executive                             Approval %          71.35
8      Executive                               Denial %           6.35
9      Executive                Average Settlement Days          47.38
10       Revenue                Total Net Billed Amount     7542050.85
11       Revenue                Total Net Billed Amount     7542050.85
12       Revenue              Average Revenue per Claim       14019.48
13       Revenue            Average Revenue per Patient       15764.26
14       Revenue             Highest Revenue Department      Emergency
15       Revenue      Highest Revenue Insurance Company  National Care
16    Collection                     Outstanding Amount     1140505.15
17    Collection                         Collection Gap     1140505.15
18    Collection           Average Collection per Claim       12430.19
19    Collection         Average Collection per Patient       13977.17
20    Collection        Average Payment Settlement Days          47.38
21    Collection                   Pending Collection %          15.12
22         Claim                 Total Claims Submitted            515
23         Claim                     High Value Claim %            0.0
24         Claim            Average Submission Attempts           1.14
25         Claim  Average Claim Processing Time (Hours)          22.24
26            AR           Average AR Balance per Claim        1589.29
27            AR         Average AR Balance per Patient        1787.08
28            AR                      Partial Payment %          26.15
29            AR                      Pending Payment %          10.77
30            AR                           Fully Paid %          63.08
31       Patient                         Total Patients            458
32       Patient                      Chronic Patient %          13.65
33       Patient                        Adult Patient %          55.96
34       Patient                       Senior Patient %          23.85
35      Provider                        Total Providers            219
36      Provider           Average Revenue per Provider       32968.17
37      Provider        Average Collection per Provider        29230.8
38      Provider            Average Provider Experience          18.98
39     Insurance              Total Insurance Companies              8
40     Insurance                     Average Coverage %          85.13
41     Insurance               High Coverage Category %          48.65
42     Insurance                  High Insurance Risk %            0.0
43   Operational                      Automation Rate %            0.0
44   Operational               Average Manual Overrides           0.13
45   Operational            Average Resource Efficiency            4.2
46   Operational             Average System Touchpoints           1.81
47     Financial                       Total Net Profit     6272798.21
48     Financial                Average Profit Margin %          87.27
49     Financial                 Total Write-Off Amount      322020.67
50     Financial             Average Operating Margin %          97.85
51     Financial         Average Billing Cost per Claim          250.0
52  Productivity             Average Productivity Index          88.22
53  Productivity                  Average Quality Score           90.6
54  Productivity                   Average Attendance %          93.64
55  Productivity                 Average Training Hours           39.8

# ************************************************************************

In [198]:
KPI_Table.to_csv("RCM_KPI_Table.csv", index=False)